#!/bin/sh

# XCode Developer Tools
xcode-select --install

# Main Sprout Wrap Items
cd ~/Downloads
git clone https://github.com/thirdwavellc/sprout-wrap.git
cd sprout-wrap
sudo gem install bundler
sudo bundle install
bundle exec soloist

# Vagrant Plugins
vagrant plugin install vagrant-berkshelf --plugin-version '>= 2.0.1'
vagrant plugin install vagrant-omnibus
vagrant plugin install vagrant-cachier
